cartesian_impedance_advanced_controller:
    type: franka_advanced_controllers/CartesianImpedanceAdvancedController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
joint_impedance_advanced_controller:
    type: franka_advanced_controllers/JointImpedanceAdvancedController
    arm_id: panda
    joint_names:
        - panda_joint1
        - panda_joint2
        - panda_joint3
        - panda_joint4
        - panda_joint5
        - panda_joint6
        - panda_joint7
